### ISSUE TITLE
"Chart & Visual data analysis" no web-components at all? 🧐

### ISSUE THREAD

**Issue by tgotwig** [nepaul/awesome-web-development#1]
I checked few libs under "Chart & Visual data analysis" and they don't look like web-components at all,
you use a web-components by something like that `<my-web-component></my-web-component>`,
but I only see regular javascript stuff inside your listings,
has nobody checked this closer before merging? 😅

**Comment by nepaul** [comment]
You are right. 
My original goal was to gather resources for web development, so I changed the name of this repository to "awesome web development."

Thanks for your feedback
